---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
#    my_passwd: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}" #generates password
    users:
      - user1
      - user2
  tasks:
    - name: Creating a new users
      user:
        name: "{{ item }}"
        password: "{{ Passw0rd | password_hash('sha512') }}"
        comment: "Created in IMSS organisation with Ansible Tower"
        update_password: always
        append: yes
        shell: "/bin/bash"
        update_password: always
        createhome: yes
      with_items:
        - "{{ users }}"
      register: user_created

    - name: Applying password security policies on the users
      shell: "chage -d 0 {{ item }}" # Change the password immediatly for the first time login user
      shell: "chage -M 30 {{ item }}" # Maximum number of days the password will expire
      with_items:
        - "{{ users }}"
      when: user_created.changed

    - name: User user_created
      debug:
        msg="{{ user_created }} with the password {{ Passw0rd }}"
      when: user_created.changed
